# Generated by Django 3.1.7 on 2022-01-02 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cors', '0002_auto_20211229_1229'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
