# Generated by Django 3.1.7 on 2022-01-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cors', '0003_auto_20220102_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('image', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
